# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- main


variables:
  isMaster: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  isNextStable: $[eq(variables['Build.SourceBranch'], 'refs/heads/next_stable')]
  isRelease: $[contains(variables['Build.SourceBranch'], 'refs/heads/20')]


jobs:
- job: Test_ceeling
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    fetchDepth: 1
    submodules: true
    clean: true
    persistCredentials: true
  - script: |
      echo $(isMaster) > test.txt
      echo $(isNextStable) >> test.txt
      echo $(isRelease) >> test.txt
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.Repository.LocalPath)/test.txt'
      artifactName: 'test'
- job: print
  pool:
    vmImage: ubuntu-latest
  steps:
  - script: |
      ./sdcard-images-utils/nxp/runme.sh 1 main
    displayName: 'test'