# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - sdcard-images-utils/nxp
    exclude:
    - sdcard-images-utils/README.md
    - sdcard-images-utils/nxp/README.md

jobs:
- job: Image_build
  pool:
    name: Default
    demands:
      - agent.name -equals ToF
  timeoutInMinutes: 120
  steps:
  - checkout: self
    fetchDepth: 1
    submodules: true
    clean: true
    persistCredentials: true
  - script: |
      echo $(Build.SourceVersion)
      cd sdcard-images-utils/nxp
      ./runme.sh 1 main
    displayName: 'test'
