# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  fetchDepth: 1
  submodules: true
  clean: true
  persistCredentials: true
- script: |
    cd sdcard-images-utils/nxp
    ./runme.sh 1 main
  displayName: 'test'
  env:
    AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
